/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortingbot;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
//import org.opencv.highgui.Highgui;
//import org.opencv.highgui.VideoCapture;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author Demy
 */
public class Gui extends javax.swing.JFrame {
    
    // definitions
    private DaemonThread myThread = null;
    int count = 0;
    VideoGrabber grabber = null;

    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();
    
    
    // class of thread
    class DaemonThread implements Runnable
    {
        protected volatile boolean runnable = false;

        @Override
        public  void run()
        {
            synchronized(this)
            {
                while(runnable)
                {
                    try
                    {
                        frame = grabber.getFrame();
                        Imgcodecs.imencode(".bmp", frame, mem);
                        Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));

                        BufferedImage buff = (BufferedImage) im;
                        Graphics g=jPanel1.getGraphics();

                        if (g.drawImage(buff, 0, 0, getWidth(), getHeight() -150 , 0, 0, buff.getWidth(), buff.getHeight(), null))

                        if(runnable == false)
                        {
                            System.out.println("GUI is going to wait()");
                            this.wait();
                        }
                     }
                     catch(Exception ex)
                     {
                        System.out.println("Error, GUI image processing failed\n");
                     }
                }
            }
         }
   }

    /**
     * Creates new form Gui
     */
    public Gui(VideoGrabber vg){
        grabber = vg;
        SetupGui();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jStart = new javax.swing.JButton();
        jPause = new javax.swing.JButton();
        jManuel = new javax.swing.JButton();
        jAuto = new javax.swing.JButton();
        jAdvance = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jLeft = new javax.swing.JButton();
        jRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        jStart.setText("Start");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });

        jPause.setText("Pause");
        jPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPauseActionPerformed(evt);
            }
        });

        jManuel.setText("Manuel Drive");
        jManuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManuelActionPerformed(evt);
            }
        });

        jAuto.setText("Auto Drive");
        jAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAutoActionPerformed(evt);
            }
        });

        jAdvance.setText("Advance");
        jAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdvanceActionPerformed(evt);
            }
        });

        jBack.setText("Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jLeft.setText("Left");
        jLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLeftActionPerformed(evt);
            }
        });

        jRight.setText("Right");
        jRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jStart)
                .addGap(18, 18, 18)
                .addComponent(jPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAdvance)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBack)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jManuel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAuto)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLeft)
                        .addGap(29, 29, 29)
                        .addComponent(jRight)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStart)
                    .addComponent(jPause)
                    .addComponent(jAdvance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLeft)
                    .addComponent(jRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAuto)
                    .addComponent(jManuel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        /// start button 
            //webSource =new VideoCapture(0); // Video capture from defult cam
            
            myThread = new DaemonThread(); // creat object of thread class
            Thread t = new Thread(myThread);
            t.setDaemon(true);
            myThread.runnable = true;
            t.start();                      // Start Thread
            jStart.setEnabled(false);  //Deactivate start button
            jPause.setEnabled(true);  // activate stop button
    }//GEN-LAST:event_jStartActionPerformed

    private void jPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPauseActionPerformed
        /// stop button 
            myThread.runnable = false;      //stop thread
            jPause.setEnabled(false);     // activate start button  
            jStart.setEnabled(true);      // deactivate sop button
            
            //webSource.release();            // stop capturing from cam
            
    }//GEN-LAST:event_jPauseActionPerformed

    private void jManuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManuelActionPerformed
        // Code to enable manuel drive..
        jManuel.setEnabled(false);      //Deactivate start button
        jAuto.setEnabled(true);         // activate stop button
        jAdvance.setEnabled(true);      // Activate advance button
        jRight.setEnabled(true);        // Deactivate Right button
        jLeft.setEnabled(true);         // Deactivate Left button
        jBack.setEnabled(true);         // Deactivate Back button
    }//GEN-LAST:event_jManuelActionPerformed

    private void jAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAutoActionPerformed
        // Code to enable auto drive.
        jManuel.setEnabled(true);       //Deactivate start button
        jAuto.setEnabled(false);        // activate stop button
        jAdvance.setEnabled(false);     // Deactivate advance button
        jRight.setEnabled(false);       // Deactivate Right button
        jLeft.setEnabled(false);        // Deactivate Left button
        jBack.setEnabled(false);        // Deactivate Back button
    }//GEN-LAST:event_jAutoActionPerformed

    private void jAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdvanceActionPerformed
        // Drive Forward
        jManuel.setEnabled(false);      //Deactivate start button
        jAdvance.setEnabled(false);    // Activate advance button
        jRight.setEnabled(true);       // Deactivate Right button
        jLeft.setEnabled(true);        // Deactivate Left button
        jBack.setEnabled(true);        // Deactivate Back button
    }//GEN-LAST:event_jAdvanceActionPerformed

    private void jRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRightActionPerformed
        // Drive Right
        jManuel.setEnabled(false);      //Deactivate start button
        jAdvance.setEnabled(true);     // Deactivate advance button
        jRight.setEnabled(false);      // Activate Right button
        jLeft.setEnabled(true);        // Deactivate Left button
        jBack.setEnabled(true);        // Deactivate Back button
    }//GEN-LAST:event_jRightActionPerformed

    private void jLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLeftActionPerformed
        // Drive Left
        jManuel.setEnabled(false);      //Deactivate start button
        jAdvance.setEnabled(true);     // Deactivate advance button
        jRight.setEnabled(true);       // Deactivate Right button
        jLeft.setEnabled(false);       // Activate Left button
        jBack.setEnabled(true);        // Deactivate Back button
    }//GEN-LAST:event_jLeftActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // Drive Back
        jManuel.setEnabled(false);      //Deactivate start button
        jAdvance.setEnabled(true);     // Deactivate advance button
        jRight.setEnabled(true);       // Deactivate Right button
        jLeft.setEnabled(true);        // Deactivate Left button
        jBack.setEnabled(false);       // Activate Back button
    }//GEN-LAST:event_jBackActionPerformed
   
//    public static void main(String args[]) {      
    public void SetupGui(){
//        System.loadLibrary(Core.NATIVE_LIBRARY_NAME); // load native library of opencv
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdvance;
    private javax.swing.JButton jAuto;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jLeft;
    private javax.swing.JButton jManuel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPause;
    private javax.swing.JButton jRight;
    private javax.swing.JButton jStart;
    // End of variables declaration//GEN-END:variables
}
